import type { Metadata } from "next"
import { Toaster } from "react-hot-toast"

import { UserService } from "@/entities/user/api/user.service"
import { Sidebar } from "@/widgets/Sidebar"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

export default async function DashboardLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  const user = await UserService.getProfile()

  return (
    <main className="flex">
      <Sidebar user={user} />
      {children}
      <Toaster toastOptions={{ iconTheme: { primary: "blue", secondary: "white" } }} />
    </main>
  )
}
