import type { Metadata } from "next"
import { Toaster } from "react-hot-toast"

import { Sidebar } from "@/widgets/Sidebar"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

export default function DashboardLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <main className="flex">
      <Sidebar />
      {children}
      <Toaster toastOptions={{ iconTheme: { primary: "blue", secondary: "white" } }} />
    </main>
  )
}
